default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  port: 5432
  host: localhost
  username: postgres
  password: research
  database: university

development:
  <<: *default
test:
  <<: *default
production:
  <<: *default
