default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  port: 5432
  host: localhost
  username: postgres
  password: 123456
  database: tracker

development:
  <<: *default
test:
  database: tracker_test
  <<: *default
production:
  <<: *default
